### ISSUE TITLE
Ability to pass a Buffer (+ AudioBuffer) as well as floats as a sample.

### ISSUE THREAD

**Issue by chr15m** [chr15m/itwriter#2]
To help with Strudel integration that @felixroos is working on.

**Comment by chr15m** [comment]
@felixroos can you tell me a bit more about what you wanted here - was it passing in an `ArrayBuffer` of floating point samples? How would you imagine stereo + samplerate be passed in this situation? And/or was it about AudioBuffer? If you can give me an example of the actual code you want working I can work to that.

**Comment by felixroos** [comment]
sry I was talking about AudioBuffer yes

**Comment by felixroos** [comment]
to add more context: strudel load samples from a url and then runs `AudioContext.decodeAudioData` to get an AudioBuffer: https://github.com/tidalcycles/strudel/blob/3cd31b229036463e49edf293cbc19a62fccbcaff/packages/superdough/sampler.mjs#L68

**Comment by chr15m** [comment]
Perfect, will fix, thank you!

**Comment by chr15m** [comment]
@felixroos have added this, thanks!
